### ISSUE TITLE
OrderedProxy is attempting to reload a deleted resource.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/activefedora-aggregation#54]
```
    Failure/Error:
     Ldp::Gone:
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:108:in `block in check_for_errors'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `tap'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `check_for_errors'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:24:in `head'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ldp-0.3.1/lib/ldp/resource.rb:48:in `head'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ldp-0.3.1/lib/ldp/resource.rb:31:in `new?'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/ldp-0.3.1/lib/ldp/resource/rdf_source.rb:31:in `graph'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/fedora_attributes.rb:45:in `resource'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/attached_files.rb:45:in `contains_assertions'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/attached_files.rb:49:in `load_attached_files'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/core.rb:46:in `reload'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/autosave_association.rb:159:in `reload'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/activefedora-aggregation-0dfe4f43e115/lib/active_fedora/aggregation/ordered_proxy.rb:33:in `each'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/activefedora-aggregation-0dfe4f43e115/lib/active_fedora/aggregation/ordered_proxy.rb:33:in `block in link_node_if_true'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/activefedora-aggregation-0dfe4f43e115/lib/active_fedora/aggregation/ordered_proxy.rb:29:in `tap'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/activefedora-aggregation-0dfe4f43e115/lib/active_fedora/aggregation/ordered_proxy.rb:29:in `link_node_if_true'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/activefedora-aggregation-0dfe4f43e115/lib/active_fedora/aggregation/ordered_proxy.rb:18:in `delete'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/record_composite.rb:14:in `block in each'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/record_composite.rb:13:in `each'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/record_composite.rb:13:in `each'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/record_composite.rb:19:in `delete'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/indirectly_contains_association.rb:63:in `delete_record'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/indirectly_contains_association.rb:58:in `block in delete_records'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/indirectly_contains_association.rb:57:in `each'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/indirectly_contains_association.rb:57:in `delete_records'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/collection_association.rb:364:in `delete_or_destroy'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/collection_association.rb:197:in `delete'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/active-fedora-9.2.0/lib/active_fedora/associations/collection_proxy.rb:569:in `delete'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/hydra-collections-486ed3b756e8/app/controllers/concerns/hydra/collections_controller_behavior.rb:182:in `remove_members_from_collection'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/hydra-collections-486ed3b756e8/app/controllers/concerns/hydra/collections_controller_behavior.rb:167:in `process_member_changes'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/hydra-collections-486ed3b756e8/app/controllers/concerns/hydra/collections_controller_behavior.rb:96:in `update'
```

**Comment by terrellt** [comment]
jcoyne: How did you get this to happen?

**Comment by terrellt** [comment]
@jcoyne I -think- this is fixed by https://github.com/projecthydra/active_fedora/pull/863. Can you confirm and then close?

**Comment by jcoyne** [comment]
@terrellt if you  bump Sufia-core to use the latest active-fedora and there are no LDP::Gone errors, then this can be closed.

**Comment by jcoyne** [comment]
fixed via https://github.com/projecthydra-labs/sufia-core/pull/58
